"""
Django settings for blueswitch project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

from config.local import *

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'push_notifications',
    'rest_framework',
    'rest_framework.authtoken',
    'blueswitch.libs.accounts',
    'blueswitch.apps.devices',
    'blueswitch.apps.toggles',
    'blueswitch.apps.users',
    'blueswitch.apps.me',
    'blueswitch.apps.baidu',
)

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)


PUSH_NOTIFICATIONS_SETTINGS = {
    "GCM_API_KEY" : "AIzaSyAY6m9XLzS3pH2VtZBdgTPdwqlTnMNvYdU",
    #"GCM_API_KEY": "AIzaSyBp8rVAUb89MUw8uxkAjoiTxpUQ-2PoovY",
    #"APNS_CERTIFICATE": os.path.join(BASE_DIR, 'triplinks/TPPro.pem'),
}

FILE_UPLOAD_HANDLERS = (
    "django_excel.ExcelMemoryFileUploadHandler",
    "django_excel.TemporaryExcelFileUploadHandler"
)
